language: elixir
elixir:
  - '1.6.6'
  - '1.7.2'
otp_release:
  - 21.0
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 100
script:
  - mix format --check-formatted
  - mix test
